Sun, 28 Jun 2015 15:18:20 web.py[line:1357] ERROR Uncaught exception GET /members/m/12 (::1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/members/m/12', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3', 'Connection': 'keep-alive', 'Cookie': '_ga=GA1.1.228519919.1435468354; _gat=1; username="2|1:0|10:1435475506|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|ed8a9417ecf9fe54b65e4a66eef14db4c257881e99842d6f11b1f50badd1f425"', 'Cache-Control': 'max-age=0', 'Referer': 'http://localhost:8080/'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 202, in get
    self.render('home_pagehome.html', user = user, articlelist = articlelist)
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 667, in render
    html = self.render_string(template_name, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 774, in render_string
    return t.generate(**namespace)
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/template.py", line 278, in generate
    return execute()
  File "home_pagehome_html.generated.py", line 65, in _tt_execute
    if handler.signeduser == user.username.decode('utf8'):  # home_page.html:9 (via home_base.html:109)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
Sun, 28 Jun 2015 15:18:20 web.py[line:1780] ERROR 500 GET /members/m/12 (::1) 80.08ms
Sun, 28 Jun 2015 15:18:21 web.py[line:1357] ERROR Uncaught exception GET /members/m/12 (::1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/members/m/12', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3', 'Connection': 'keep-alive', 'Cookie': '_ga=GA1.1.228519919.1435468354; _gat=1; username="2|1:0|10:1435475506|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|ed8a9417ecf9fe54b65e4a66eef14db4c257881e99842d6f11b1f50badd1f425"', 'Cache-Control': 'max-age=0', 'Referer': 'http://localhost:8080/'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 202, in get
    self.render('home_pagehome.html', user = user, articlelist = articlelist)
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 667, in render
    html = self.render_string(template_name, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 774, in render_string
    return t.generate(**namespace)
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/template.py", line 278, in generate
    return execute()
  File "home_pagehome_html.generated.py", line 65, in _tt_execute
    if handler.signeduser == user.username.decode('utf8'):  # home_page.html:9 (via home_base.html:109)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
Sun, 28 Jun 2015 15:18:21 web.py[line:1780] ERROR 500 GET /members/m/12 (::1) 36.17ms
Sun, 28 Jun 2015 15:19:36 web.py[line:1780] WARNING 404 GET /static/images/avatar-01.svg (::1) 8.15ms
Sun, 28 Jun 2015 15:19:39 web.py[line:1780] WARNING 404 GET /static/images/avatar-01.svg (::1) 2.34ms
